output "openai_endpoint" {
  description = "Azure OpenAI endpoint URL. Set as OPENAI_BASE_URL in app/.azure-agent."
  value       = azurerm_cognitive_account.openai.endpoint
}

output "openai_api_key" {
  description = "Primary access key for the Azure OpenAI account. Set as OPENAI_API_KEY in app/.azure-agent."
  value       = azurerm_cognitive_account.openai.primary_access_key
  sensitive   = true
}

output "model_deployment_name" {
  description = "Name of the deployed model. Set as OPENAI_DEPLOYMENT_NAME in app/.azure-agent."
  value       = azurerm_cognitive_deployment.model.name
}

output "ai_foundry_hub_id" {
  description = "Resource ID of the Azure AI Foundry Hub."
  value       = azurerm_ai_foundry.hub.id
}

output "ai_foundry_project_id" {
  description = "Resource ID of the Azure AI Foundry Project."
  value       = azurerm_ai_foundry_project.main.id
}

output "app_env_vars" {
  description = "Run 'terraform output -raw app_env_vars' and append to app/.azure-agent to configure the app."
  sensitive   = true
  value       = <<-EOT

    # Azure AI Foundry / Azure OpenAI — generated by terraform
    AI_PROVIDER=openai
    OPENAI_API_KEY=${azurerm_cognitive_account.openai.primary_access_key}
    OPENAI_BASE_URL=${azurerm_cognitive_account.openai.endpoint}
    OPENAI_API_VERSION=2024-10-21
    OPENAI_DEPLOYMENT_NAME=${azurerm_cognitive_deployment.model.name}
  EOT
}
